var classes = [
    {
        "name": "App\\Cart\\CartCollection",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "instance",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "currentInstance",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "get",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateDraftAttributes",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "emptyDraft",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "removeDraft",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "content",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getContent",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "keys",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addItemToDraft",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "draftHasItem",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateDraftItem",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "removeItemFromDraft",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "count",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isEmpty",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hasContent",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 19,
        "nbMethods": 19,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 18,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 25,
        "ccn": 7,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Cart\\TransactionDraft",
            "App\\Cart\\Item",
            "App\\Cart\\TransactionDraft",
            "App\\Product"
        ],
        "parents": [],
        "lcom": 2,
        "length": 184,
        "vocabulary": 28,
        "volume": 884.55,
        "difficulty": 19.64,
        "effort": 17369.41,
        "level": 0.05,
        "bugs": 0.29,
        "time": 965,
        "intelligentContent": 45.05,
        "number_operators": 40,
        "number_operands": 144,
        "number_operators_unique": 6,
        "number_operands_unique": 22,
        "cloc": 3,
        "loc": 124,
        "lloc": 121,
        "mi": 44.92,
        "mIwoC": 32.99,
        "commentWeight": 11.93,
        "kanDefect": 0.59,
        "relativeStructuralComplexity": 289,
        "relativeDataComplexity": 0.77,
        "relativeSystemComplexity": 289.77,
        "totalStructuralComplexity": 5491,
        "totalDataComplexity": 14.61,
        "totalSystemComplexity": 5505.61,
        "package": "App\\Cart\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "App\\Cart\\CashDraft",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "App\\Cart\\TransactionDraft"
        ],
        "parents": [
            "App\\Cart\\TransactionDraft"
        ],
        "lcom": 0,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 0,
        "number_operands": 2,
        "number_operators_unique": 0,
        "number_operands_unique": 2,
        "cloc": 3,
        "loc": 10,
        "lloc": 7,
        "mi": 116.84,
        "mIwoC": 79.32,
        "commentWeight": 37.52,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Cart\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Cart\\CreditDraft",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "App\\Cart\\TransactionDraft"
        ],
        "parents": [
            "App\\Cart\\TransactionDraft"
        ],
        "lcom": 0,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 0,
        "number_operands": 2,
        "number_operators_unique": 0,
        "number_operands_unique": 2,
        "cloc": 3,
        "loc": 10,
        "lloc": 7,
        "mi": 116.84,
        "mIwoC": 79.32,
        "commentWeight": 37.52,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Cart\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Cart\\Item",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateAttribute",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setItemDiscount",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Product"
        ],
        "parents": [],
        "lcom": 1,
        "length": 58,
        "vocabulary": 11,
        "volume": 200.65,
        "difficulty": 11.71,
        "effort": 2350.44,
        "level": 0.09,
        "bugs": 0.07,
        "time": 131,
        "intelligentContent": 17.13,
        "number_operators": 17,
        "number_operands": 41,
        "number_operators_unique": 4,
        "number_operands_unique": 7,
        "cloc": 3,
        "loc": 42,
        "lloc": 39,
        "mi": 68.75,
        "mIwoC": 48.63,
        "commentWeight": 20.12,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 0.78,
        "relativeSystemComplexity": 4.78,
        "totalStructuralComplexity": 12,
        "totalDataComplexity": 2.33,
        "totalSystemComplexity": 14.33,
        "package": "App\\Cart\\",
        "pageRank": 0.06,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "App\\Cart\\TransactionDraft",
        "interface": false,
        "abstract": true,
        "methods": [
            {
                "name": "toArray",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "items",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addItem",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "removeItem",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "empty",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSubtotal",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTotal",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getItemsCount",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTotalQty",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDiscountTotal",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateItem",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "search",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "searchItemKeyFor",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getExchange",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getNewInvoiceNo",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getItemsArray",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 18,
        "nbMethods": 18,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 17,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 23,
        "ccn": 6,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Cart\\Item",
            "App\\Product",
            "App\\Product",
            "App\\Transaction",
            "App\\Transaction"
        ],
        "parents": [],
        "lcom": 1,
        "length": 169,
        "vocabulary": 44,
        "volume": 922.64,
        "difficulty": 9.71,
        "effort": 8959.36,
        "level": 0.1,
        "bugs": 0.31,
        "time": 498,
        "intelligentContent": 95.01,
        "number_operators": 46,
        "number_operands": 123,
        "number_operators_unique": 6,
        "number_operands_unique": 38,
        "cloc": 3,
        "loc": 114,
        "lloc": 111,
        "mi": 46.25,
        "mIwoC": 33.82,
        "commentWeight": 12.43,
        "kanDefect": 0.59,
        "relativeStructuralComplexity": 256,
        "relativeDataComplexity": 1.14,
        "relativeSystemComplexity": 257.14,
        "totalStructuralComplexity": 4608,
        "totalDataComplexity": 20.47,
        "totalSystemComplexity": 4628.47,
        "package": "App\\Cart\\",
        "pageRank": 0.08,
        "afferentCoupling": 3,
        "efferentCoupling": 3,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\Console\\Kernel",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "schedule",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "commands",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Console\\Kernel",
            "Illuminate\\Console\\Scheduling\\Schedule"
        ],
        "parents": [
            "Illuminate\\Foundation\\Console\\Kernel"
        ],
        "lcom": 2,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 0,
        "number_operands": 2,
        "number_operators_unique": 0,
        "number_operands_unique": 2,
        "cloc": 19,
        "loc": 31,
        "lloc": 12,
        "mi": 121.05,
        "mIwoC": 74.22,
        "commentWeight": 46.83,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 0.5,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "App\\Console\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Exceptions\\Handler",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "report",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "unauthenticated",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Illuminate\\Foundation\\Exceptions\\Handler",
            "Exception",
            "parent",
            "Exception",
            "parent",
            "Illuminate\\Auth\\AuthenticationException"
        ],
        "parents": [
            "Illuminate\\Foundation\\Exceptions\\Handler"
        ],
        "lcom": 3,
        "length": 17,
        "vocabulary": 8,
        "volume": 51,
        "difficulty": 2.17,
        "effort": 110.5,
        "level": 0.46,
        "bugs": 0.02,
        "time": 6,
        "intelligentContent": 23.54,
        "number_operators": 4,
        "number_operands": 13,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 30,
        "loc": 50,
        "lloc": 20,
        "mi": 106,
        "mIwoC": 59.39,
        "commentWeight": 46.6,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.93,
        "relativeSystemComplexity": 16.93,
        "totalStructuralComplexity": 48,
        "totalDataComplexity": 2.8,
        "totalSystemComplexity": 50.8,
        "package": "App\\Exceptions\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Api\\ProductsController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "search",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Product"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "lcom": 1,
        "length": 40,
        "vocabulary": 16,
        "volume": 160,
        "difficulty": 5,
        "effort": 800,
        "level": 0.2,
        "bugs": 0.05,
        "time": 44,
        "intelligentContent": 32,
        "number_operators": 10,
        "number_operands": 30,
        "number_operators_unique": 4,
        "number_operands_unique": 12,
        "cloc": 0,
        "loc": 18,
        "lloc": 18,
        "mi": 56.92,
        "mIwoC": 56.92,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.4,
        "relativeSystemComplexity": 16.4,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0.4,
        "totalSystemComplexity": 16.4,
        "package": "App\\Http\\Controllers\\Api\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\ChangePasswordController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getChangePassword",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "postChangePassword",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "lcom": 3,
        "length": 42,
        "vocabulary": 28,
        "volume": 201.91,
        "difficulty": 2.1,
        "effort": 424.01,
        "level": 0.48,
        "bugs": 0.07,
        "time": 24,
        "intelligentContent": 96.15,
        "number_operators": 7,
        "number_operands": 35,
        "number_operators_unique": 3,
        "number_operands_unique": 25,
        "cloc": 5,
        "loc": 31,
        "lloc": 26,
        "mi": 81.86,
        "mIwoC": 52.72,
        "commentWeight": 29.14,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.37,
        "relativeSystemComplexity": 64.37,
        "totalStructuralComplexity": 192,
        "totalDataComplexity": 1.11,
        "totalSystemComplexity": 193.11,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Auth\\LoginController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "username",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "App\\Http\\Controllers\\Controller"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "lcom": 2,
        "length": 7,
        "vocabulary": 7,
        "volume": 19.65,
        "difficulty": 0.5,
        "effort": 9.83,
        "level": 2,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 39.3,
        "number_operators": 1,
        "number_operands": 6,
        "number_operators_unique": 1,
        "number_operands_unique": 6,
        "cloc": 20,
        "loc": 34,
        "lloc": 14,
        "mi": 112.19,
        "mIwoC": 65.81,
        "commentWeight": 46.38,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 3,
        "package": "App\\Http\\Controllers\\Auth\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\BackupsController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "download",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "restore",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "upload",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 12,
        "ccn": 7,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "File",
            "Illuminate\\Http\\Request",
            "BackupManager\\Filesystems\\Destination",
            "App\\Http\\Requests\\BackupUploadRequest"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "lcom": 6,
        "length": 88,
        "vocabulary": 29,
        "volume": 427.5,
        "difficulty": 9.7,
        "effort": 4148.72,
        "level": 0.1,
        "bugs": 0.14,
        "time": 230,
        "intelligentContent": 44.05,
        "number_operators": 27,
        "number_operands": 61,
        "number_operators_unique": 7,
        "number_operands_unique": 22,
        "cloc": 42,
        "loc": 98,
        "lloc": 56,
        "mi": 84.95,
        "mIwoC": 42.5,
        "commentWeight": 42.45,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 169,
        "relativeDataComplexity": 0.64,
        "relativeSystemComplexity": 169.64,
        "totalStructuralComplexity": 1014,
        "totalDataComplexity": 3.86,
        "totalSystemComplexity": 1017.86,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\CartController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "add",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "addDraftItem",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateDraftItem",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "removeDraftItem",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "empty",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "remove",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "proccess",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 12,
        "nbMethods": 12,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 12,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 19,
        "ccn": 8,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "App\\Cart\\CartCollection",
            "Illuminate\\Http\\Request",
            "Illuminate\\Http\\Request",
            "App\\Product",
            "Illuminate\\Http\\Request",
            "App\\Cart\\CashDraft",
            "App\\Cart\\CreditDraft",
            "Illuminate\\Http\\Request",
            "App\\Product",
            "App\\Cart\\Item",
            "Illuminate\\Http\\Request",
            "Illuminate\\Http\\Request",
            "Illuminate\\Http\\Request",
            "Illuminate\\Http\\Request",
            "Illuminate\\Http\\Request"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "lcom": 1,
        "length": 215,
        "vocabulary": 63,
        "volume": 1285.12,
        "difficulty": 8.74,
        "effort": 11227.85,
        "level": 0.11,
        "bugs": 0.43,
        "time": 624,
        "intelligentContent": 147.09,
        "number_operators": 49,
        "number_operands": 166,
        "number_operators_unique": 6,
        "number_operands_unique": 57,
        "cloc": 0,
        "loc": 102,
        "lloc": 102,
        "mi": 33.34,
        "mIwoC": 33.34,
        "commentWeight": 0,
        "kanDefect": 0.64,
        "relativeStructuralComplexity": 529,
        "relativeDataComplexity": 0.73,
        "relativeSystemComplexity": 529.73,
        "totalStructuralComplexity": 6348,
        "totalDataComplexity": 8.71,
        "totalSystemComplexity": 6356.71,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 7,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Controller",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Illuminate\\Routing\\Controller"
        ],
        "parents": [
            "Illuminate\\Routing\\Controller"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 0,
        "loc": 5,
        "lloc": 5,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.09,
        "afferentCoupling": 11,
        "efferentCoupling": 1,
        "instability": 0.08,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\LogFilesController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "download",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 4,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "File"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "lcom": 3,
        "length": 46,
        "vocabulary": 18,
        "volume": 191.82,
        "difficulty": 5.38,
        "effort": 1032.86,
        "level": 0.19,
        "bugs": 0.06,
        "time": 57,
        "intelligentContent": 35.62,
        "number_operators": 18,
        "number_operands": 28,
        "number_operators_unique": 5,
        "number_operands_unique": 13,
        "cloc": 1,
        "loc": 30,
        "lloc": 29,
        "mi": 65.53,
        "mIwoC": 51.58,
        "commentWeight": 13.95,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 1.53,
        "relativeSystemComplexity": 17.53,
        "totalStructuralComplexity": 48,
        "totalDataComplexity": 4.6,
        "totalSystemComplexity": 52.6,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\ProductsController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "priceList",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 6,
        "ccnMethodMax": 4,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Product",
            "App\\Product",
            "Illuminate\\Http\\Request",
            "App\\Product",
            "Illuminate\\Http\\Request",
            "App\\Product",
            "Illuminate\\Http\\Request",
            "App\\Product",
            "App\\Product"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "lcom": 5,
        "length": 116,
        "vocabulary": 43,
        "volume": 629.45,
        "difficulty": 7.46,
        "effort": 4695.33,
        "level": 0.13,
        "bugs": 0.21,
        "time": 261,
        "intelligentContent": 84.38,
        "number_operators": 24,
        "number_operands": 92,
        "number_operators_unique": 6,
        "number_operands_unique": 37,
        "cloc": 2,
        "loc": 51,
        "lloc": 49,
        "mi": 57.82,
        "mIwoC": 42.72,
        "commentWeight": 15.1,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 0.55,
        "relativeSystemComplexity": 144.55,
        "totalStructuralComplexity": 720,
        "totalDataComplexity": 2.77,
        "totalSystemComplexity": 722.77,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\Reports\\SalesController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "daily",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "monthly",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "yearly",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getMonthlyReports",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getYearlyReports",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Transaction",
            "Illuminate\\Http\\Request",
            "Illuminate\\Http\\Request",
            "DB",
            "DB",
            "DB",
            "DB",
            "DB",
            "DB",
            "DB",
            "DB",
            "DB"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "lcom": 3,
        "length": 139,
        "vocabulary": 36,
        "volume": 718.62,
        "difficulty": 6.75,
        "effort": 4850.68,
        "level": 0.15,
        "bugs": 0.24,
        "time": 269,
        "intelligentContent": 106.46,
        "number_operators": 31,
        "number_operands": 108,
        "number_operators_unique": 4,
        "number_operands_unique": 32,
        "cloc": 5,
        "loc": 58,
        "lloc": 53,
        "mi": 63.95,
        "mIwoC": 41.98,
        "commentWeight": 21.97,
        "kanDefect": 0.61,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.62,
        "relativeSystemComplexity": 81.62,
        "totalStructuralComplexity": 405,
        "totalDataComplexity": 3.1,
        "totalSystemComplexity": 408.1,
        "package": "App\\Http\\Controllers\\Reports\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\TransactionsController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "receipt",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "pdf",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Transaction",
            "App\\Transaction",
            "App\\Transaction",
            "App\\Transaction",
            "PDF"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "lcom": 4,
        "length": 65,
        "vocabulary": 23,
        "volume": 294.03,
        "difficulty": 5.16,
        "effort": 1516.58,
        "level": 0.19,
        "bugs": 0.1,
        "time": 84,
        "intelligentContent": 57.01,
        "number_operators": 16,
        "number_operands": 49,
        "number_operators_unique": 4,
        "number_operands_unique": 19,
        "cloc": 1,
        "loc": 33,
        "lloc": 32,
        "mi": 62.8,
        "mIwoC": 49.48,
        "commentWeight": 13.32,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.63,
        "relativeSystemComplexity": 49.63,
        "totalStructuralComplexity": 196,
        "totalDataComplexity": 2.5,
        "totalSystemComplexity": 198.5,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\UnitsController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 5,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\Unit",
            "App\\Unit",
            "Illuminate\\Http\\Request",
            "App\\Unit",
            "Illuminate\\Http\\Request",
            "App\\Unit",
            "Illuminate\\Http\\Request",
            "App\\Unit"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "lcom": 4,
        "length": 68,
        "vocabulary": 30,
        "volume": 333.67,
        "difficulty": 5.3,
        "effort": 1768.44,
        "level": 0.19,
        "bugs": 0.11,
        "time": 98,
        "intelligentContent": 62.96,
        "number_operators": 15,
        "number_operands": 53,
        "number_operators_unique": 5,
        "number_operands_unique": 25,
        "cloc": 0,
        "loc": 37,
        "lloc": 37,
        "mi": 47.45,
        "mIwoC": 47.45,
        "commentWeight": 0,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.81,
        "relativeSystemComplexity": 49.81,
        "totalStructuralComplexity": 196,
        "totalDataComplexity": 3.25,
        "totalSystemComplexity": 199.25,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Controllers\\UsersController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "store",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 7,
        "ccnMethodMax": 3,
        "externals": [
            "App\\Http\\Controllers\\Controller",
            "Illuminate\\Http\\Request",
            "App\\User",
            "App\\User",
            "Illuminate\\Http\\Request",
            "App\\User",
            "Illuminate\\Http\\Request",
            "App\\User",
            "Illuminate\\Http\\Request",
            "App\\User"
        ],
        "parents": [
            "App\\Http\\Controllers\\Controller"
        ],
        "lcom": 2,
        "length": 108,
        "vocabulary": 37,
        "volume": 562.62,
        "difficulty": 8.32,
        "effort": 4682.46,
        "level": 0.12,
        "bugs": 0.19,
        "time": 260,
        "intelligentContent": 67.6,
        "number_operators": 22,
        "number_operands": 86,
        "number_operators_unique": 6,
        "number_operands_unique": 31,
        "cloc": 13,
        "loc": 60,
        "lloc": 47,
        "mi": 76.34,
        "mIwoC": 43.33,
        "commentWeight": 33.01,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0.65,
        "relativeSystemComplexity": 81.65,
        "totalStructuralComplexity": 324,
        "totalDataComplexity": 2.6,
        "totalSystemComplexity": 326.6,
        "package": "App\\Http\\Controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Kernel",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Illuminate\\Foundation\\Http\\Kernel"
        ],
        "parents": [
            "Illuminate\\Foundation\\Http\\Kernel"
        ],
        "lcom": 0,
        "length": 10,
        "vocabulary": 9,
        "volume": 31.7,
        "difficulty": 0,
        "effort": 0,
        "level": 1.8,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 57.06,
        "number_operators": 0,
        "number_operands": 10,
        "number_operators_unique": 0,
        "number_operands_unique": 9,
        "cloc": 20,
        "loc": 34,
        "lloc": 14,
        "mi": 110.74,
        "mIwoC": 64.35,
        "commentWeight": 46.38,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\EncryptCookies",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Illuminate\\Cookie\\Middleware\\EncryptCookies"
        ],
        "parents": [
            "Illuminate\\Cookie\\Middleware\\EncryptCookies"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 5,
        "loc": 10,
        "lloc": 5,
        "mi": 215.46,
        "mIwoC": 171,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\Middleware\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\RedirectIfAuthenticated",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Closure",
            "Illuminate\\Support\\Facades\\Auth"
        ],
        "parents": [],
        "lcom": 1,
        "length": 10,
        "vocabulary": 6,
        "volume": 25.85,
        "difficulty": 1.75,
        "effort": 45.24,
        "level": 0.57,
        "bugs": 0.01,
        "time": 3,
        "intelligentContent": 14.77,
        "number_operators": 3,
        "number_operands": 7,
        "number_operators_unique": 2,
        "number_operands_unique": 4,
        "cloc": 9,
        "loc": 20,
        "lloc": 11,
        "mi": 110.22,
        "mIwoC": 67.12,
        "commentWeight": 43.1,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.67,
        "relativeSystemComplexity": 5.67,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 1.67,
        "totalSystemComplexity": 5.67,
        "package": "App\\Http\\Middleware\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\TrimStrings",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Illuminate\\Foundation\\Http\\Middleware\\TrimStrings"
        ],
        "parents": [
            "Illuminate\\Foundation\\Http\\Middleware\\TrimStrings"
        ],
        "lcom": 0,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 0,
        "number_operands": 2,
        "number_operators_unique": 0,
        "number_operands_unique": 2,
        "cloc": 5,
        "loc": 10,
        "lloc": 5,
        "mi": 126.97,
        "mIwoC": 82.51,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\Middleware\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\TrustProxies",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Fideloper\\Proxy\\TrustProxies"
        ],
        "parents": [
            "Fideloper\\Proxy\\TrustProxies"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 10,
        "loc": 16,
        "lloc": 6,
        "mi": 218.04,
        "mIwoC": 171,
        "commentWeight": 47.04,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\Middleware\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Middleware\\VerifyCsrfToken",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken"
        ],
        "parents": [
            "Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken"
        ],
        "lcom": 0,
        "length": 0,
        "vocabulary": 0,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 0,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 0,
        "number_operators_unique": 0,
        "number_operands_unique": 0,
        "cloc": 5,
        "loc": 10,
        "lloc": 5,
        "mi": 215.46,
        "mIwoC": 171,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "App\\Http\\Middleware\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Http\\Requests\\BackupUploadRequest",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "authorize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "messages",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getValidatorInstance",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Illuminate\\Foundation\\Http\\FormRequest",
            "parent"
        ],
        "parents": [
            "Illuminate\\Foundation\\Http\\FormRequest"
        ],
        "lcom": 4,
        "length": 23,
        "vocabulary": 14,
        "volume": 87.57,
        "difficulty": 2.8,
        "effort": 245.19,
        "level": 0.36,
        "bugs": 0.03,
        "time": 14,
        "intelligentContent": 31.27,
        "number_operators": 9,
        "number_operands": 14,
        "number_operators_unique": 4,
        "number_operands_unique": 10,
        "cloc": 10,
        "loc": 37,
        "lloc": 27,
        "mi": 90.96,
        "mIwoC": 54.91,
        "commentWeight": 36.05,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 1.2,
        "relativeSystemComplexity": 17.2,
        "totalStructuralComplexity": 64,
        "totalDataComplexity": 4.8,
        "totalSystemComplexity": 68.8,
        "package": "App\\Http\\Requests\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "App\\Product",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "getPrice",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "unit",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "lcom": 2,
        "length": 19,
        "vocabulary": 13,
        "volume": 70.31,
        "difficulty": 2.89,
        "effort": 203.11,
        "level": 0.35,
        "bugs": 0.02,
        "time": 11,
        "intelligentContent": 24.34,
        "number_operators": 6,
        "number_operands": 13,
        "number_operators_unique": 4,
        "number_operands_unique": 9,
        "cloc": 0,
        "loc": 16,
        "lloc": 16,
        "mi": 60.4,
        "mIwoC": 60.4,
        "commentWeight": 0,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.75,
        "relativeSystemComplexity": 2.75,
        "totalStructuralComplexity": 2,
        "totalDataComplexity": 3.5,
        "totalSystemComplexity": 5.5,
        "package": "App\\",
        "pageRank": 0.26,
        "afferentCoupling": 6,
        "efferentCoupling": 1,
        "instability": 0.14,
        "violations": {}
    },
    {
        "name": "App\\Providers\\AppServiceProvider",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "register",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Support\\ServiceProvider",
            "DB",
            "Validator"
        ],
        "parents": [
            "Illuminate\\Support\\ServiceProvider"
        ],
        "lcom": 2,
        "length": 16,
        "vocabulary": 11,
        "volume": 55.35,
        "difficulty": 2.25,
        "effort": 124.54,
        "level": 0.44,
        "bugs": 0.02,
        "time": 7,
        "intelligentContent": 24.6,
        "number_operators": 4,
        "number_operands": 12,
        "number_operators_unique": 3,
        "number_operands_unique": 8,
        "cloc": 11,
        "loc": 26,
        "lloc": 15,
        "mi": 104.28,
        "mIwoC": 62,
        "commentWeight": 42.28,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.2,
        "relativeSystemComplexity": 16.2,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 0.4,
        "totalSystemComplexity": 32.4,
        "package": "App\\Providers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Providers\\AuthServiceProvider",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Support\\Providers\\AuthServiceProvider"
        ],
        "parents": [
            "Illuminate\\Foundation\\Support\\Providers\\AuthServiceProvider"
        ],
        "lcom": 1,
        "length": 3,
        "vocabulary": 3,
        "volume": 4.75,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 9.51,
        "number_operators": 0,
        "number_operands": 3,
        "number_operators_unique": 0,
        "number_operands_unique": 3,
        "cloc": 11,
        "loc": 20,
        "lloc": 9,
        "mi": 119.93,
        "mIwoC": 74.31,
        "commentWeight": 45.62,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "package": "App\\Providers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Providers\\BroadcastServiceProvider",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Support\\ServiceProvider",
            "Illuminate\\Support\\Facades\\Broadcast"
        ],
        "parents": [
            "Illuminate\\Support\\ServiceProvider"
        ],
        "lcom": 1,
        "length": 1,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 1,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 5,
        "loc": 14,
        "lloc": 9,
        "mi": 210.96,
        "mIwoC": 171,
        "commentWeight": 39.96,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "package": "App\\Providers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Providers\\EventServiceProvider",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Support\\Providers\\EventServiceProvider",
            "parent"
        ],
        "parents": [
            "Illuminate\\Foundation\\Support\\Providers\\EventServiceProvider"
        ],
        "lcom": 1,
        "length": 2,
        "vocabulary": 2,
        "volume": 2,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 4,
        "number_operators": 0,
        "number_operands": 2,
        "number_operators_unique": 0,
        "number_operands_unique": 2,
        "cloc": 11,
        "loc": 20,
        "lloc": 9,
        "mi": 122.56,
        "mIwoC": 76.94,
        "commentWeight": 45.62,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "package": "App\\Providers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Providers\\RouteServiceProvider",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "map",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "mapWebRoutes",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "mapApiRoutes",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Support\\Providers\\RouteServiceProvider",
            "parent",
            "Illuminate\\Support\\Facades\\Route",
            "Illuminate\\Support\\Facades\\Route"
        ],
        "parents": [
            "Illuminate\\Foundation\\Support\\Providers\\RouteServiceProvider"
        ],
        "lcom": 2,
        "length": 10,
        "vocabulary": 6,
        "volume": 25.85,
        "difficulty": 0,
        "effort": 0,
        "level": 1.2,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 31.02,
        "number_operators": 0,
        "number_operands": 10,
        "number_operators_unique": 0,
        "number_operands_unique": 6,
        "cloc": 33,
        "loc": 55,
        "lloc": 22,
        "mi": 107.29,
        "mIwoC": 60.69,
        "commentWeight": 46.6,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 49,
        "totalStructuralComplexity": 196,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 196,
        "package": "App\\Providers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "App\\Transaction",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "getRouteKeyName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getItemsCountAttribute",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getExchange",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "user",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "lcom": 3,
        "length": 30,
        "vocabulary": 17,
        "volume": 122.62,
        "difficulty": 4.17,
        "effort": 510.93,
        "level": 0.24,
        "bugs": 0.04,
        "time": 28,
        "intelligentContent": 29.43,
        "number_operators": 10,
        "number_operands": 20,
        "number_operators_unique": 5,
        "number_operands_unique": 12,
        "cloc": 0,
        "loc": 25,
        "lloc": 25,
        "mi": 54.61,
        "mIwoC": 54.61,
        "commentWeight": 0,
        "kanDefect": 0.38,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 2.13,
        "relativeSystemComplexity": 3.13,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 8.5,
        "totalSystemComplexity": 12.5,
        "package": "App\\",
        "pageRank": 0.1,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "App\\Unit",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "products",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "parents": [
            "Illuminate\\Database\\Eloquent\\Model"
        ],
        "lcom": 1,
        "length": 4,
        "vocabulary": 4,
        "volume": 8,
        "difficulty": 0.5,
        "effort": 4,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 16,
        "number_operators": 1,
        "number_operands": 3,
        "number_operators_unique": 1,
        "number_operands_unique": 3,
        "cloc": 0,
        "loc": 10,
        "lloc": 10,
        "mi": 71.73,
        "mIwoC": 71.73,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0.5,
        "relativeSystemComplexity": 1.5,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0.5,
        "totalSystemComplexity": 1.5,
        "package": "App\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 1,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "App\\User",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "setPasswordAttribute",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Foundation\\Auth\\User"
        ],
        "parents": [
            "Illuminate\\Foundation\\Auth\\User"
        ],
        "lcom": 1,
        "length": 10,
        "vocabulary": 6,
        "volume": 25.85,
        "difficulty": 0.9,
        "effort": 23.26,
        "level": 1.11,
        "bugs": 0.01,
        "time": 1,
        "intelligentContent": 28.72,
        "number_operators": 1,
        "number_operands": 9,
        "number_operators_unique": 1,
        "number_operands_unique": 5,
        "cloc": 10,
        "loc": 21,
        "lloc": 11,
        "mi": 111.1,
        "mIwoC": 67.26,
        "commentWeight": 43.84,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 1,
        "package": "App\\",
        "pageRank": 0.03,
        "afferentCoupling": 2,
        "efferentCoupling": 1,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "CreateUsersTable",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Illuminate\\Support\\Facades\\Schema",
            "Illuminate\\Support\\Facades\\Schema"
        ],
        "parents": [
            "Illuminate\\Database\\Migrations\\Migration"
        ],
        "lcom": 2,
        "length": 13,
        "vocabulary": 6,
        "volume": 33.6,
        "difficulty": 0,
        "effort": 0,
        "level": 0.92,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 31.02,
        "number_operators": 0,
        "number_operands": 13,
        "number_operators_unique": 0,
        "number_operands_unique": 6,
        "cloc": 10,
        "loc": 29,
        "lloc": 19,
        "mi": 100.75,
        "mIwoC": 61.28,
        "commentWeight": 39.47,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 36,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 72,
        "package": "App\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CreateProductsTable",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Illuminate\\Support\\Facades\\Schema",
            "Illuminate\\Support\\Facades\\Schema"
        ],
        "parents": [
            "Illuminate\\Database\\Migrations\\Migration"
        ],
        "lcom": 2,
        "length": 15,
        "vocabulary": 8,
        "volume": 45,
        "difficulty": 0,
        "effort": 0,
        "level": 1.07,
        "bugs": 0.02,
        "time": 0,
        "intelligentContent": 48,
        "number_operators": 0,
        "number_operands": 15,
        "number_operators_unique": 0,
        "number_operands_unique": 8,
        "cloc": 10,
        "loc": 29,
        "lloc": 19,
        "mi": 99.86,
        "mIwoC": 60.39,
        "commentWeight": 39.47,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 36,
        "totalStructuralComplexity": 72,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 72,
        "package": "App\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CreateTransactionsTable",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Illuminate\\Support\\Facades\\Schema",
            "Illuminate\\Support\\Facades\\Schema"
        ],
        "parents": [
            "Illuminate\\Database\\Migrations\\Migration"
        ],
        "lcom": 2,
        "length": 21,
        "vocabulary": 11,
        "volume": 72.65,
        "difficulty": 0,
        "effort": 0,
        "level": 1.05,
        "bugs": 0.02,
        "time": 0,
        "intelligentContent": 76.11,
        "number_operators": 0,
        "number_operands": 21,
        "number_operators_unique": 0,
        "number_operands_unique": 11,
        "cloc": 10,
        "loc": 32,
        "lloc": 22,
        "mi": 95.64,
        "mIwoC": 57.55,
        "commentWeight": 38.09,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 81,
        "totalStructuralComplexity": 162,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 162,
        "package": "App\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "CreateProductUnitsTable",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 2,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Migrations\\Migration",
            "Illuminate\\Support\\Facades\\Schema",
            "Illuminate\\Support\\Facades\\Schema"
        ],
        "parents": [
            "Illuminate\\Database\\Migrations\\Migration"
        ],
        "lcom": 2,
        "length": 9,
        "vocabulary": 5,
        "volume": 20.9,
        "difficulty": 0,
        "effort": 0,
        "level": 1.11,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 0,
        "number_operands": 9,
        "number_operators_unique": 0,
        "number_operands_unique": 5,
        "cloc": 10,
        "loc": 26,
        "lloc": 16,
        "mi": 105.34,
        "mIwoC": 64.36,
        "commentWeight": 40.98,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 16,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 32,
        "package": "App\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "DatabaseSeeder",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Seeder"
        ],
        "parents": [
            "Illuminate\\Database\\Seeder"
        ],
        "lcom": 1,
        "length": 1,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 1,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 5,
        "loc": 13,
        "lloc": 8,
        "mi": 211.98,
        "mIwoC": 171,
        "commentWeight": 40.98,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "package": "App\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "UsersTableSeeder",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "Illuminate\\Database\\Seeder",
            "App\\User"
        ],
        "parents": [
            "Illuminate\\Database\\Seeder"
        ],
        "lcom": 1,
        "length": 8,
        "vocabulary": 8,
        "volume": 24,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 48,
        "number_operators": 0,
        "number_operands": 8,
        "number_operators_unique": 0,
        "number_operands_unique": 8,
        "cloc": 5,
        "loc": 13,
        "lloc": 8,
        "mi": 111.48,
        "mIwoC": 70.5,
        "commentWeight": 40.98,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 1,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 1,
        "package": "App\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    }
]